### ISSUE TITLE
Use parameter for GHA instead of global `env` var

### ISSUE THREAD

**Issue by dajudge** [AtomicJar/testcontainers-cloud-setup-action#2]
Would it make sense to parameterize the action instead of using a global `env` var?

E.g.:

```
name: Java CI with Maven

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: "Run checks"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup testcontainers-cloud
        uses: atomicjar/testcontainers-cloud-setup-action@main
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          java-version: '8.0.345'
          distribution: temurin
      - name: Build with Maven
        run: mvn -V -B verify
```
